# Generated by Django 5.0.7 on 2024-07-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0003_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
